<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="WizardCorrelationProperties.wsdl" targetNamespace="http://enterprise.netbeans.org/bpel/WizardCorrelationProperties" xmlns:tns="http://enterprise.netbeans.org/bpel/WizardCorrelationProperties" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:ns="http://j2ee.netbeans.org/wsdl/LoanAmountProxy/src/LoanAmountProxyWSDL" xmlns:ns1="http://j2ee.netbeans.org/wsdl/LoanAmountProxy/src/LoanAmountCallBackWSDL">
    <import namespace="http://j2ee.netbeans.org/wsdl/LoanAmountProxy/src/LoanAmountProxyWSDL" location="LoanAmountProxyWSDL.wsdl"/>
    <import namespace="http://j2ee.netbeans.org/wsdl/LoanAmountProxy/src/LoanAmountCallBackWSDL" location="LoanAmountCallBackWSDL.wsdl"/>
    <vprop:property name="wzrd_prop_string_string" type="xsd:string"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_string_string" messageType="ns:LoanAmountProxyWSDLOperationRequest" part="LoanAmount"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_string_string" messageType="ns1:LoanAmountCallBackWSDLOperationRequest" part="LoanAmount"/>
    <vprop:property name="wzrd_prop_string_string2" type="xsd:string"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_string_string2" messageType="ns:LoanAmountProxyWSDLOperationRequest" part="InterestRate"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_string_string2" messageType="ns1:LoanAmountCallBackWSDLOperationRequest" part="InterestRate"/>
    <vprop:property name="wzrd_prop_string_string3" type="xsd:string"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_string_string3" messageType="ns:LoanAmountProxyWSDLOperationRequest" part="Months"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_string_string3" messageType="ns1:LoanAmountCallBackWSDLOperationRequest" part="Months"/>
</definitions>
