<?xml version="1.0" encoding="UTF-8"?>
<definitions name="MortageAndLoanServiceWSDL" targetNamespace="http://j2ee.netbeans.org/wsdl/MortageAndLoanService/src/MortageAndLoanServiceWSDL"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/MortageAndLoanService/src/MortageAndLoanServiceWSDL" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types/>
    <message name="MortgageConversionAndLoanServiceWSDLOperationRequest">
        <part name="MortgageYears" type="xsd:int"/>
        <part name="MortgageInterest" type="xsd:double"/>
        <part name="MortgageLoanAmount" type="xsd:double"/>
        <part name="MortgageAnnualTax" type="xsd:double"/>
        <part name="MortgageAnnualInsurance" type="xsd:double"/>
        <part name="CurrencyFrom" type="xsd:string"/>
        <part name="CurrencyTo" type="xsd:string"/>
        <part name="LoanAmount" type="xsd:string"/>
        <part name="InterestRate" type="xsd:string"/>
        <part name="Months" type="xsd:string"/>
    </message>
    <message name="MortageConversionAndLoanServiceWSDLOperationResponse">
        <part name="MortgageTotalAmountConverted" type="xsd:string"/>
        <part name="MonthlyTaxRate" type="xsd:string"/>
        <part name="MonthlyInsuranceRate" type="xsd:string"/>
        <part name="LoanMonthlyPaymentResult" type="xsd:string"/>
    </message>
    <message name="To_fault_Message">
        <part name="FaultMessage" type="xsd:string"/>
    </message>
    <portType name="MortgageConversionAndLoanServiceWSDLPortType">
        <operation name="getMortgageAndLoan">
            <input name="input1" message="tns:MortgageConversionAndLoanServiceWSDLOperationRequest"/>
            <output name="output1" message="tns:MortageConversionAndLoanServiceWSDLOperationResponse"/>
            <fault name="to_fault" message="tns:To_fault_Message"/>
        </operation>
    </portType>
    <binding name="MortgageConversionAndLoanServiceWSDLBinding" type="tns:MortgageConversionAndLoanServiceWSDLPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="getMortgageAndLoan">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/MortageAndLoanService/src/MortageAndLoanServiceWSDL"/>
            </input>
            <output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/MortageAndLoanService/src/MortageAndLoanServiceWSDL"/>
            </output>
            <fault name="to_fault">
                <soap:fault name="to_fault"/>
            </fault>
        </operation>
    </binding>
    <service name="MortgageConversionAndLoanServiceWSDLService">
        <port name="MortgageConversionAndLoanServiceWSDLPort" binding="tns:MortgageConversionAndLoanServiceWSDLBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/MortageAndLoanServiceWSDLService/MortageAndLoanServiceWSDLPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="MortgageConversionAndLoanServiceWSDL">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="MortgageConversionAndLoanServiceWSDLPortTypeRole" portType="tns:MortgageConversionAndLoanServiceWSDLPortType"/>
    </plnk:partnerLinkType>
</definitions>
